version: "3.8"

services:
  # Load balancer container
  lb:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Customized configuration
    ports:
      - "443:80"  # Public port for load-balanced access
    networks:
      - internal  # Connects to web servers
      - external  # Connects to host network

  # Web server containers (multiple instances)
  web:
    image: python:3.8-alpine
    build: .
    command: ["python", "server.py", "localhost", "8000"]
    ports:
      - "8000:8000"  # Internal port for web server
    networks:
      - internal  # Connects to load balancer

  # Nginx Proxy container
  proxy:
    image: jwilder/nginx-proxy:alpine
    restart: unless-stopped
    volumes:
      - ./certs:/etc/nginx/certs:rw  # Optional volume for certificates (see note below)
      - ./letsencrypt:/etc/letsencrypt  # Persistent volume for Let's Encrypt data (recommended)
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - internal  # Connects to web server
      - external  # Connects to host network

networks:
  # Internal network for communication between containers
  internal:
    external: false  # Prevents external access directly to web servers

  # External network for public access through load balancer
  external:
    external: true  # Allows access from host network interface

volumes:
  certs:

