---
- name: Install web server components
  hosts: all
  become: yes
  tasks:
    - name: Test connectivity
      ping:

    - name: Install Apache2, PHP, and PHP module for Apache
      apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
        state: present

    - name: Ensure Apache is restarted
      service:
        name: apache2
        state: restarted

- name: Setup Python module and web server environment
  hosts: all
  become: yes
  tasks:
    - name: Install Python and pip3
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Ensure the directory exists/Create directory
      ansible.builtin.file:
        path: /home/vs5938/
        state: directory

    - name: Copy server.py script
      ansible.builtin.copy:
        src: ../Code/server.py
        dest: /home/vs5938/server.py
        mode: '0755'

    - name: Copy HTTP_parser.py script
      ansible.builtin.copy:
        src: ../Code/http_parser.py
        dest: /home/vs5938/http_parser.py
        mode: '0755'
    - name: Copy PHP script
      ansible.builtin.copy:
        src: ../Code/greetings.php
        dest: /home/vs5938/greetings.php
        mode: '0755'
    - name: Copy PHP script - $_GET
      ansible.builtin.copy:
        src: ../Code/D_GET_page.php
        dest: /home/vs5938/D_GET_page.php
        mode: '0755'

    - name: Check if cert.pem exists
      ansible.builtin.stat:
        path: /home/vs5938/demo.crt
      register: cert_result

    - name: Check if key.pem exists
      ansible.builtin.stat:
        path: /home/vs5938/demo.key
      register: key_result

    - name: Move SSL certificate to /home/vs5938
      ansible.builtin.copy:
        src: ../demo.crt
        dest: /usr/local/share/ca-certificates/custom_certificate.crt
      when: not cert_result.stat.exists

    - name: Move SSL key to /home/vs5938
      ansible.builtin.copy:
        src: ../demo.key
        dest: /home/vs5938/demo.key
      when: not key_result.stat.exists

    - name: Update CA certificates to trust the copied certificate
      ansible.builtin.command:
        cmd: update-ca-certificates
      register: update_output

    - name: Verify update output
      ansible.builtin.debug:
        var: update_output.stdout_lines


    - name: Create systemd service file for web server
      ansible.builtin.template:
        src: start_server.service.j2
        dest: /etc/systemd/system/start_server.service

    - name: Ensure the server log file exists
      ansible.builtin.file:
        path: /home/vs5938/server.log
        state: touch

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable and start Python server service
      ansible.builtin.systemd:
        name: start_server
        state: started
        enabled: yes

    - name: Ensure the server log file exists
      ansible.builtin.file:
        path: /home/vs5938/server_output.log
        state: touch

    - name: Start Python web server
      command: sudo python3 /home/vs5938/server.py 127.0.0.1 8080 /home/vs5938/demo.crt /home/vs5938/demo.key
      become: yes
      register: command_output
      async: 10
      poll: 0

    - name: Display web server output
      command: cat /home/vs5938/server_output.log
      register: server_output

    - name: Print server output
      debug:
        var: server_output.stdout